services:
  nestproject:
    container_name: 'resturantProject'
    restart: always
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: ./src/DockerFile
    ports:
      - '9000:9000'
    volumes:
      - .:/home/node/app
    links:
      - mongodb
    depends_on:
      - mongodb
    networks:
      - backend

  mongodb:
    image: mongo:7.0.2
    container_name: nestjs-database-connection-mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - backend  

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - 'resturant_redis:/data'
    networks:
      - backend

volumes:
  mongodb_data_container:
    driver: local
  resturant_redis:
    driver: local  

networks:
  backend:
    driver: bridge
